# Generated by Django 3.0.3 on 2020-02-18 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('search_x', models.FloatField()),
                ('search_y', models.FloatField()),
                ('operation', models.CharField(choices=[('N', 'Nearest'), ('F', 'Furthest')], default='N', max_length=1)),
                ('points', models.PositiveIntegerField()),
            ],
        ),
    ]
